### ISSUE TITLE
Artboard not animating when loading multiple Artboards from single rive file 

### ISSUE THREAD

**Issue by IbrahimYildirim** [rive-app/rive-flutter#176]
Hi,

I just started using Rive and I love it! It's really amazing what you guys have created.

I'm using it on a new project, where I will be using have 4 Artboards in a single screen, but for this example I'm only showing 2.

**Artboards**
`Welcome` : Has a StateMachine with many different animations
`Play Button`: Has only a single loop animation (similar to the rest of the Artboards)

I really want to make the UX even smooth by reducing loading times. 

In the `initState` I load the .riv file and call the following code

```
  _initRiveFile(ByteData riveFile) {
    final file = RiveFile.import(riveFile);
    final artboard = file.artboardByName('Welcome');
    final playArtboard = file.artboardByName('Play Button');
    if (artboard != null) {
      final controller = StateMachineController.fromArtboard(artboard, 'WelcomeState');
      if (controller != null) {
        artboard.addController(controller);
        _rivePlayArtboard!.addController(playController);
        _isMan = controller.findInput<bool>('isMan') as SMIBool;
        _artStep = controller.findInput<double>('Step') as SMINumber;
        setState(() {
           _rivePlayArtboard = playArtboard;
          _riveMainArtboard = artboard;
        });
      }
    } else {
      print('Error loading artboard :(');
    }
  }
```

My build method is something like

```
  Widget build(BuildContext context) {
    return Stack(
      fit: StackFit.expand,
      children: [
        _riveMainArtboard == null
            ? Container()
            : Positioned.fill(
                child: Rive(
                  artboard: _riveMainArtboard!,
                  fit: BoxFit.fill,
                ),
              ),
        Align(
            alignment: Alignment.center,
            child: _rivePlayArtboard == null
                ? Container()
                : Rive(
                    artboard: _rivePlayArtboard!,
                  )),
      ],
    );
  }
```

When I do this this, my `_riveMainArtboard` which has a `StateMachine` is animating, but the `_rivePlayArtboard` is rendering the design but not animating/calling the only animation which it has.

When i use `RiveAnimation.asset(...)` for the `Play Button` it automatically starts playing the default animation. But it feels like it takes a second to load all the 4 animations if I use `RiveAnimation.asset()` directly in the build method, so I was just looking for ways to improve the loading.

Am I missing something? Do I need to add a controller/animation for the artboard to animate the only animation it has?

**Comment by HayesGordon** [comment]
The part that is missing is the `playController` from this sample. For that `playController` assuming it is a simple animation, be sure to add the correct animation name that you want to play:
```dart
SimpleAnimation playController = SimpleAnimation('YourAnimationName');
```

That should work, if it does not please reopen this issue. I'm closing this for now due to age.

With regards to your question on RiveAnimation.asset feeling slower. That could happen if the Rive file has a lot of assets that need to be loaded (for example images).

If you're displaying the same Rive file in multiple places it'll be better to do what you're doing - reading in the RiveFile yourself and creating the Artboard + Controllers. This will also allow you to control the instance of the RiveFile and cache the value.
