### ISSUE TITLE
The autoplay parameter doesn't work on Flutter

### ISSUE THREAD

**Issue by tommybuonomo** [rive-app/rive-flutter#259]
### Description
I am looking for a way to hide the animation until I decide to display it on the screen. This animation has to play on top of the widgets which are under it.
 I have several problems when trying to do so:
- The `autoplay: false` parameter does nothing, my state machine animation plays when the widget `RiveAnimation.asset` is built for the first time
- The `onStart` and `onStop` listeners are not notified when the animation starts and finish at beginning
- I don't want any gesture on the Rive widget, because I can't touch the other widgets on the screen, is there a way to disable/absorb the touch on the artboard?

### Steps To Reproduce
In the `initState` of the widget state:
```dart
_coinsController = OneShotAnimation(
      'coins_animation',
      autoplay: false,
      onStart: () {
        print("OnStart");
      },
      onStop: () {
        print("OnStop");
      },
    )..isActive = false;
```

In the `build`:
```dart
            child: RiveAnimation.asset(
              "assets/lottie/coins.riv",
              stateMachines: ["coins_animation"],
              alignment: Alignment.topCenter,
              fit: BoxFit.fitWidth,
              controllers: [_coinsController],
            )
```

#### Source `.riv`/`.rev` file
<-- 	
[coins.riv.zip](https://github.com/rive-app/rive-flutter/files/9649118/coins.riv.zip)

#### Screenshots
https://user-images.githubusercontent.com/15737675/192363219-cd4792b6-d96b-4696-8c70-4e79e735fa60.mp4

### Device & Versions (please complete the following information)
- Device: Android Physical device (OnePlus 8 Pro)
- OS: Android SDK API Level 33
- Flutter Version: 
```
Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e3c29ec00c (12 days ago) • 2022-09-14 08:46:55 -0500
Engine • revision a4ff2c53d8
Tools • Dart 2.18.1 • DevTools 2.15.0
```

**Comment by zplata** [comment]
Hey there! A few things going on - I see that you defined the `stateMachines` property on the `RiveAnimation.asset()`; this is what's showing on the screen in your recording. The `_coinsController` I think is a bit misleading here. That class is mainly for singular linear animations (the states that make up the state machine). 

Instead of using `OneShotAnimation` here, you might try the `StateMachineController` and its `isActive` property to set it to false or true. You can set that property to true when you're ready to play the state machine. And because you want to control when the state machine `coins_animation` plays, you'd also want to remove the `stateMachines` property on the `RiveAnimation.asset()`, as that will guarantee it autoplays once the widget mounts.

Instead of `onStart` and `onStop`, I'd add a callback for `onStateChange` when creating your StateMachineController (see the example below) to look for the first/last state in the state machine to get a similar functionality.

Regarding the gesture on the Rive widget, that's something I think we can definitely add a parameter for on the `RiveAnimation` widget. The reason we have touch listeners on there is due to our Listeners feature, but if you don't have any, we could probably skip adding those listeners on that widget.

**Example**: https://gist.github.com/zplata/e22895cd1350213be25497dc6cba818c

**Comment by tommybuonomo** [comment]
Hello @zplata 
Really nice response and support, thanks a lot 👌  I can now manage the animation as I wanted!

About the gesture, I think it could be very interesting to have such a parameter for the next release 🙂

**Comment by HayesGordon** [comment]
Closing this as it appears to be solved 🙂. The `RiveAnimation` widget will only add touch events if needed.

But if needed it can be disabled by wrapping with an [AbsorbPointer](https://api.flutter.dev/flutter/widgets/AbsorbPointer-class.html) widget. Or alternatively, making use of the `Rive` widget directly.
