### ISSUE TITLE
Changing a shape's color at runtime doesn't work if the animation varies opacity

### ISSUE THREAD

**Issue by spegoraro** [rive-app/rive-flutter#287]
### Description
Changing paint properties at runtime doesn't have any effect if the animation changes layer or fill opacity.

### Steps To Reproduce
1. Load an animation that does not change opacity (either layer or fill, doesn't matter)
2. In `onInit` get a reference to the shape component and change its fill color via `fill.paint.color`.
3. Observe that it works correctly
4. Repeat with an animation that does change opacity (either layer or fill, doesn't matter)
5. Observe that it uses the fill set in the design and not the one just set at runtime.

#### Source `.riv`/`.rev` file
See `main_button.riv.zip` (zipped to please github).
This changes the button's opacity in the `Delay` and `Press` timelines. If I remove the opacity change then the colors change correcly at runtime.

### Expected behavior
The opacity change should not force the design fill color and should just apply opacity to whichever color was set on the shape.

#### Screenshots
None, sorry.

### Device & Versions (please complete the following information)
- Device: iOS Simulator
- OS: iOS 16.2
- Flutter Version:
```
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (9 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1
```
[main_button.riv.zip](https://github.com/rive-app/rive-flutter/files/10563480/main_button.riv.zip)

**Comment by wenyue** [comment]
+1 same question

**Comment by HayesGordon** [comment]
Hi 👋 , in the future there might be a better API to do data binding between the editor and the runtime.

In order to do more advanced operations for the Flutter runtime, you will need to create a custom Rive render object. I've created and example that does the above (setting the colour, and respecting the current colour alpha value).

Note that with custom render object you can do more advanced things, for example, getting the world transform position of a component and overlay it with a Flutter widget, or do custom painting, etc.

Here is the sample project: https://github.com/HayesGordon/rive_flutter_runtime_color_change_example

I'm closing this issue as there are already another similar issue: https://github.com/rive-app/rive-flutter/issues/164

**Comment by spegoraro** [comment]
Ok, thanks for the example!

**Comment by snipd-mikel** [comment]
I found out that if you animate the opacity via the layer instead of via the color opacity, you can programatically the color, by also changing the `paintMutator.color` property:

```dart
RiveAnimation.asset(
    'assets/rive/animation.riv',
    artboard: 'artboard',
    animations: const ['animation'],
    onInit: (artboard) {
      _changeRiveColors(artboard, {
        'background': Colors.transparent,
        'star_color': Colors.red,
      });
    },
  );
  
  ....
  
  void _changeRiveColors(Artboard artboard, Map<String, Color> replacements) {
  final fills = <Fill>{};

  artboard.forEachComponent((component) {
    if (component is Fill) {
      fills.add(component);
    }
  });

  for (final fill in fills) {
    if (replacements.containsKey(fill.name)) {
      fill.paint.color = replacements[fill.name]!;
      final paintMutator = fill.paintMutator;
      if (paintMutator is SolidColor) {
        paintMutator.color = replacements[fill.name]!;
      }
    }
  }
}

```

**Comment by HayesGordon** [comment]
Ah yeah that's a cleaner way! @snipd-mikel
