### ISSUE TITLE
Events don't fire when animation loaded from file

### ISSUE THREAD

**Issue by FilledStacks** [rive-app/rive-flutter#402]
### Description

Event listeners do not fire when loading a rive animation from a file directly. 

### Steps To Reproduce

Clone [this repo](https://github.com/FilledStacks/rive_event_bug) and run it. 

Tapping on the button in the middle of the screen should print out an event but it doesn't. 

To test that the event is set up properly you can comment out line `42 -> 47` in `main.dart` then uncomment line `49 -> 64`.

When tapping on the button in the middle of the screen you'll see the event printing out. 

#### Source `.riv`/`.rev` file

You can download the .riv [file here](https://github.com/FilledStacks/rive_event_bug/blob/main/assets/tidyplan_ui.riv)

### Expected behavior
Event listeners should fire regardless of how a rive animation is loaded.

### Device & Versions (please complete the following information)
- Device: Android real device (Samsung galaxy s21 fan, Android emulator)
e.g.:
```
Flutter 3.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5dcb86f68f (6 weeks ago) • 2024-05-09 07:39:20 -0500
Engine • revision f6344b75dc
Tools • Dart 3.4.0 • DevTools 2.34.3
```

**Comment by HayesGordon** [comment]
Hey!

You're using two separate instances of the Artboard. Basically adding the event listener on an instance that is never passed to the widget. When manually creating the artboard like this, always call `instance()`.

```dart
benefitOneArtboard = riveFile.artboardByName('benefit-1-view')!.instance(); // add .instance()
```

And remove it from the widget creation:
```dart
body: Rive(
  artboard: benefitOneArtboard, // remove .instance()
  useArtboardSize: true,
  fit: BoxFit.cover,
  enablePointerEvents: true,
),
```

You'll also note that the event is triggered twice in the "working" example because you've added it twice: once to the "main" loaded artboard and again on the instanced version.

Closing this issue but let me know if you run into problems.

**Comment by FilledStacks** [comment]
I knew I was overlooking something silly. 

Thanks Gordon!
